# Generated by Django 2.2.4 on 2019-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='referent',
            field=models.BooleanField(default=False),
        ),
    ]
