# Generated by Django 2.2.4 on 2019-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190911_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='referent',
            field=models.BooleanField(default=False, help_text='Nimmt diese Person als Referent an der Veranstaltung teil?', verbose_name='Referent'),
        ),
    ]
