# Generated by Django 2.2.4 on 2019-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190911_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='eingegangen'),
        ),
    ]
