# Generated by Django 2.2.4 on 2019-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_bookingoption_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoption',
            name='nights',
            field=models.IntegerField(blank=True, null=True, verbose_name='Übernachtungen'),
        ),
    ]
