# Generated by Django 2.2.4 on 2019-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20191008_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoption',
            name='abbreviation',
            field=models.CharField(default='', help_text='EZ, DZ oder Extern', max_length=20, verbose_name='Kürzel'),
            preserve_default=False,
        ),
    ]
