# Generated by Django 2.2.4 on 2019-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20191009_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='Übernachtung',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='occupants',
            field=models.IntegerField(default=1, help_text='Anzahl der Gäste im Zimmer', verbose_name='Gäste'),
            preserve_default=False,
        ),
    ]
