# Generated by Django 2.2.4 on 2019-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20191018_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='Inhalt',
            field=models.TextField(blank=True, help_text='Inhalt der Veranstaltung für E-Mail-Betreff und URL, z.B. Streitgespräch zwischen Merting und dem Papst', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='Titel',
            field=models.TextField(blank=True, help_text='Offizieller Titel der Veranstaltung für Einladungen', max_length=200),
        ),
    ]
