# Generated by Django 2.2.4 on 2019-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20191020_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='confirm_with_address',
            field=models.BooleanField(default=True, help_text='Wenn angekreuzt, bekommen TN eine Bestätigung unter Angabe der Adresse. Wenn nicht, muss die Adresse separat mitgeteilt werden.', verbose_name='mit Adresse bestätigen'),
        ),
    ]
