# Generated by Django 2.2.4 on 2019-10-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_veranstaltung_confirm_with_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='bookingoption',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formentries', to='crm.BookingOption', verbose_name='Buchungsoption'),
        ),
    ]
