# Generated by Django 2.2.4 on 2019-10-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20191025_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='erteilt')),
                ('text', models.TextField(max_length=500)),
                ('formentry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.FormEntry')),
            ],
        ),
    ]
