# Generated by Django 2.2.4 on 2019-10-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20191025_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='entry_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
