# Generated by Django 2.2.4 on 2019-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20191025_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='E_Mail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-Mail'),
        ),
    ]
