# Generated by Django 2.2.4 on 2019-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20191025_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2001-01-01', verbose_name='eingegangen'),
            preserve_default=False,
        ),
    ]
