# Generated by Django 2.2.4 on 2019-10-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20191025_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='record_created_db',
        ),
    ]
