# Generated by Django 2.2.4 on 2019-10-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20191028_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Category'),
        ),
    ]
