# Generated by Django 2.2.4 on 2019-10-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0027_communication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtemplate',
            name='message_part',
            field=models.ForeignKey(help_text='Teil der Nachricht, z.B. Betreffzeile, Textkörper', on_delete=django.db.models.deletion.CASCADE, to='crm.MessagePart'),
        ),
        migrations.AlterField(
            model_name='templateconnection',
            name='content_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_templates', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='templateconnection',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='inheritance',
            unique_together={('parent_model', 'child_model')},
        ),
    ]
