# Generated by Django 2.2.4 on 2019-10-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20191029_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='Format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Format', verbose_name='Format dieses Moduls'),
        ),
    ]
