# Generated by Django 2.2.4 on 2019-11-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20191103_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateconnection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='crm.DbTemplate'),
        ),
    ]
