# Generated by Django 2.2.4 on 2019-11-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20191103_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='bookingoption',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formentries', to='crm.BookingOption', verbose_name='Buchungsoption'),
        ),
    ]
