# Generated by Django 2.2.4 on 2020-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20191109_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='description',
            field=models.TextField(blank=True, help_text='Text für die Anzeige auf den öffentlichen Anmeldeseiten (html benutzen)', verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='link_active',
            field=models.BooleanField(default=False, help_text='Wenn angekreuzt, ist der Link auf der Übersichtsseite zur Anmeldungseite aktiv.', verbose_name='Link aktiv'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='public',
            field=models.BooleanField(blank=True, default=False, help_text='Wenn dieser Haken gesetzt ist, werden einzelne Veranstalungen dieses Moduls öffentlich auf der Seite angezeigt, sofern der Haken »Seite startklar« auch gesetzt ist.', verbose_name='öffentlich'),
        ),
    ]
