# Generated by Django 2.2.4 on 2020-01-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20200118_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='Format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Format', verbose_name='Format dieses Moduls'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='Format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.Format'),
        ),
    ]
