# Generated by Django 2.2.4 on 2020-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20200119_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='Kostenstelle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
