# Generated by Django 2.2.4 on 2020-01-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_format_kostenstelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='Kostenstelle',
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='Kostenstelle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateconnection',
            name='content_model',
            field=models.ForeignKey(blank=True, help_text='This single field is alternative to the generic relation consisting of content_type and object id, providing one fallback template for all objects of type ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_templates', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='templateconnection',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Foreign key of object type specified in content_type', null=True),
        ),
    ]
