# Generated by Django 2.2.4 on 2020-01-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_auto_20200120_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoption',
            name='formlabel',
        ),
        migrations.AlterField(
            model_name='bookingoption',
            name='abbreviation',
            field=models.CharField(help_text='Kennzeichnung in der Statistik auf der Anmeldungsseite (EZ, DZ-1 oder Extern)', max_length=20, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='bookingoption',
            name='formvalue',
            field=models.CharField(blank=True, help_text='Dieser Wert wird dem externen Benutzer auf dem Anmeldeformular angezeigt. Bitte auf Übereinstimmung mit anderen Angaben prüfen.', max_length=250, null=True, verbose_name='angezeigter Text'),
        ),
        migrations.AlterField(
            model_name='bookingoption',
            name='roomtype',
            field=models.ForeignKey(blank=True, help_text='Diese Auswahl bedingt die Anzahl der Teilnehmer, die mit einer Buchung verbunden sind.', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.RoomType', verbose_name='EZ/DZ/Extern'),
        ),
    ]
