# Generated by Django 2.2.4 on 2020-01-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20200120_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoption',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='bookingoption',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='bookingoption',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingoptions', to='crm.Format', verbose_name='Format'),
        ),
    ]
