# Generated by Django 2.2.4 on 2020-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20200120_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='Inhalt',
            field=models.CharField(blank=True, help_text='Inhalt der Veranstaltung für E-Mail-Betreff und URL, z.B. Streitgespräch zwischen Merting und dem Papst', max_length=200, null=True),
        ),
    ]
