# Generated by Django 2.2.9 on 2020-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20200120_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='site_listed',
            field=models.BooleanField(default=False, help_text='Wenn angekreuzt, wird die Seite in Übersichten wie erasmus-stiftung.de/veranstaltungen aufgelistet.', verbose_name='Seite in Übersichten aufgelistet'),
        ),
    ]
