# Generated by Django 2.2.9 on 2020-01-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_veranstaltung_site_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoption',
            name='sorted_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Reihenfolge'),
        ),
    ]
