# Generated by Django 2.2.9 on 2020-01-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_bookingoption_sorted_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoption',
            options={'ordering': ['bookingoption_order'], 'verbose_name': 'Buchungsoptionen', 'verbose_name_plural': 'Buchungsoptionen'},
        ),
        migrations.RenameField(
            model_name='bookingoption',
            old_name='sorted_order',
            new_name='bookingoption_order',
        ),
    ]
