# Generated by Django 2.2.9 on 2020-01-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_auto_20200125_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbtemplate',
            options={'ordering': ['dbtemplate_order'], 'verbose_name': 'Vorlage', 'verbose_name_plural': 'Vorlagen'},
        ),
        migrations.AddField(
            model_name='dbtemplate',
            name='dbtemplate_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
