# Generated by Django 2.2.9 on 2020-01-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_auto_20200125_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='DbTemplate',
            field=models.ForeignKey(help_text='Vorlage, die zur Erzeugung des Textes benutzt wurde.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.DbTemplate'),
        ),
    ]
