# Generated by Django 2.2.9 on 2020-01-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_consent_dbtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consent',
            old_name='DbTemplate',
            new_name='dbtemplate',
        ),
    ]
