# Generated by Django 2.2.9 on 2020-02-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_veranstaltung_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('registrations_allowed', models.IntegerField(help_text='Anzahl der Anmeldungen, die mit diesem Code möglich sind. 0 = unbegrenzt.', verbose_name='erlaubte Anmeldungen')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Veranstaltung', verbose_name='Veranstaltung')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Person', verbose_name='Person')),
            ],
            options={
                'unique_together': {('event', 'person')},
            },
        ),
        migrations.AddField(
            model_name='formentry',
            name='invitation_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='formentries', to='crm.InvitationCode', verbose_name='Einladungscode'),
        ),
    ]
