# Generated by Django 2.2.9 on 2020-02-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_auto_20200210_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='crm.Veranstaltung', verbose_name='Veranstaltung'),
        ),
    ]
