# Generated by Django 2.2.10 on 2020-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_auto_20200210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='html_invitation',
            field=models.TextField(blank=True, help_text='HTML, der als E-Mail-Einladung verschickt wird - Werte in {Klammern} werden serienbriefmäßig ersetzt.'),
        ),
    ]
