# Generated by Django 2.2.10 on 2020-03-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_auto_20200303_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagepart',
            options={'ordering': ['messagepart_order'], 'verbose_name': 'Nachrichtenteil', 'verbose_name_plural': 'Nachrichtenteile'},
        ),
        migrations.AddField(
            model_name='communication',
            name='formentry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.FormEntry', verbose_name='Formulareintrag'),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='messagepart_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Reihenfolge'),
        ),
    ]
