# Generated by Django 2.2.10 on 2020-03-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0057_auto_20200303_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateconnection',
            unique_together={('template', 'content_type', 'object_id')},
        ),
    ]
