# Generated by Django 2.2.10 on 2020-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_auto_20200305_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepart',
            name='name',
            field=models.CharField(help_text='Name des Nachrichtenteils, i.e. Betreffzeile, Textkörper', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
