# Generated by Django 2.2.11 on 2020-04-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_auto_20200319_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='type',
        ),
    ]
